src/objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BusDataBase.cls
public class BusDataBase {
    
    public static List< ModelBox.Bus > queryGetBuses(String busPartner, Boolean available) {
        
        List <Bus__c> neededBuses         = new List<Bus__c>();
        List<ModelBox.Bus> busesForReturn = new  List<ModelBox.Bus>();
        
        neededBuses = [SELECT id, name, available__c, account__c  
                       FROM Bus__c 
                       WHERE account__c = :busPartner
                       AND available__c = :available];
        
        for(Bus__c nededBus : neededBuses){            
            busesForReturn.add(new ModelBox.Bus(nededBus));            
        }        
        return  busesForReturn;
    }
    public static Integer queryGetCountOfBuses(String busPartner) {       
        return [SELECT count()  
                FROM Bus__c 
                WHERE account__c = :busPartner];
    }
    
    public static void queryUpsertBus (ModelBox.Bus newBus) {    
        Database.upsert(newBus.unMap());    
    } 
    
    
    public static void queryToDelete(ModelBox.Bus targetBus){
        Database.delete(targetBus.unMap());
    }  
}