src/objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bus_Line__c.object
<CustomObject>
    <fields>
        <fullName>Bus__c</fullName>
        <label>Bus</label>
        <referenceTo>Bus__c</referenceTo>
        <relationshipLabel>Bus_Line_relations</relationshipLabel>
        <relationshipName>Bus_Line_relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <referenceTo>Line__c</referenceTo>
        <relationshipLabel>Bus_Line_relations</relationshipLabel>
        <relationshipName>Bus_Line_relations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus_Line</label>
    <nameField>
        <displayFormat>BL-{0000000}</displayFormat>
        <label>Bus_Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus_Line_relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Line__c.object
<CustomObject>
    <label>Line</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BusLineService.cls
public  class BusLineService {
        
    public static List< ModelBox.Line > getAllLines(){
       
       if(CheckPermissions.checkAccessFLS('Line__c',new List<String> { 'Name','Id' })){
            List<ModelBox.Line> returnLines = new List<ModelBox.Line>();
            for(Line__c line : BusLineDatabaseQueries.getAllLinesQuery()){
                returnLines.add(new ModelBox.Line(line));
            }            
            return returnLines;
        }
       else{           
           throw new CustomException('InvalidAccess','You do not have rights for access this object',  1);
        }
    }
    
    public static List< ModelBox.Bus > getBusLines(Id busOwner){ 
        
        List< ModelBox.Bus > busWithLines = new List< ModelBox.Bus >();

        if(CheckPermissions.checkAccessFLS('Bus__c',      new List<String>{'Id' , 'Name', 'Available__c', 'Account__c'})&&
           CheckPermissions.checkAccessFLS('Bus_Line__c', new List<String>{'Bus__c','Line__c'})&&
           CheckPermissions.checkAccessFLS('Line__c',     new List<String>{'Name','Id'})){        
            
            for(Bus__c bus : BusLineDatabaseQueries.getBusLinesQuery(busOwner)){     
            busWithLines.add(new ModelBox.Bus(bus,retLinesOfBus(bus)));
            }
        }
        else{
            throw new CustomException('InvalidAccess','You do not have rights for access this object',  1);
        }
        return busWithLines;
    }

    public static void addNewBusRoute(ModelBox.Bus_Line newRoute){
            if(CheckPermissions.checkInsertRights('Bus_Line__c')){
                BusLineDatabaseQueries.insertBusLine(newRoute.convertToCustObj());
            }
            else{
                throw new CustomException('InvalidInsert','Sorry but You do not have rights to add a new route for the bus ',1);
            } 
    }    
    
    public static void removeBusRoute(Id busForRem, Id lineForRem){      
            if(CheckPermissions.checkDeleteRights('Bus_Line__c')){
                BusLineDatabaseQueries.deleteBusLine(busForRem, lineForRem);
            }
            else{
                throw new CustomException('InvalidDelete','Sorry but You do not have the right to remove the bus from the route ',1);
            }
    }  

    public static List <ModelBox.Line> retLinesOfBus(Bus__c currentBus){ // helper for create List of bus lines

    List<ModelBox.Line> busLines = new List<ModelBox.Line>();
    for (sObject busLine : currentBus.getSObjects('Bus_Line_relations__r')) {

        sObject line             = busLine.getsObject('Line__r');
        Id lineId                = (Id) line.get('Id');
        String lineName          = (String) line.get('Name');  
        ModelBox.Line lineForAdd = new ModelBox.Line(lineId,lineName);

        busLines.add(lineForAdd);
        }        
    return busLines;
    }
}