src/objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bus_Line__c.object
<CustomObject>
    <fields>
        <fullName>Bus__c</fullName>
        <label>Bus</label>
        <referenceTo>Bus__c</referenceTo>
        <relationshipLabel>Bus_Line_relations</relationshipLabel>
        <relationshipName>Bus_Line_relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <referenceTo>Line__c</referenceTo>
        <relationshipLabel>Bus_Line_relations</relationshipLabel>
        <relationshipName>Bus_Line_relations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus_Line</label>
    <nameField>
        <displayFormat>BL-{0000000}</displayFormat>
        <label>Bus_Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus_Line_relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Line__c.object
<CustomObject>
    <label>Line</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BusLineDatabaseQueries.cls
public class BusLineDatabaseQueries {
    
    public static List<Bus__c> getBusLinesQuery (Id busOwner){ // Select all buslines which have relation with busOwner
        return [ SELECT Id , Name, Available__c, Account__c, (Select Line__r.Name, Line__r.Id 
                                                             FROM Bus_Line_relations__r) 
                FROM Bus__c
                WHERE Account__c = :busOwner];
    }
    
    public static List<Line__c> getAllLinesQuery (){ // Select all lines
        return [ SELECT Id , Name  FROM Line__c ORDER BY name];       
    }

    public static void insertBusLine(Bus_Line__c busLineForInsert){
        Database.insert(busLineForInsert);
    }

    public static void deleteBusLine(Id busForRem, Id lineForRem){
       delete [SELECT ID FROM Bus_Line__c WHERE Bus__c =: busForRem AND Line__c =:lineForRem ];
    }
}