src/objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BusService.cls
public class  BusService {
    
    public static List< ModelBox.Bus > getBuses(String busPartner, Boolean available) { 
        if(CheckPermissions.checkAccessFLS('Bus__c',new List<String>{'id', 'name', 'available__c', 'account__c'})){
            return BusDataBase.queryGetBuses(busPartner, available);
        }
        else{
            throw new CustomException('InvalidAccess','Sorry but You do not have permission to view the list of buses',1);
        }        
    }
        
    public static Integer getTotalBusesNumber(String busPartner) {       
            return BusDataBase.queryGetCountOfBuses(busPartner);
    } 
    
    public static void upsertBus(ModelBox.Bus bus,Boolean isItNew) {
      
        if(CheckPermissions.checkUpdateRights('Bus__c')&& isItNew || !isItNew && CheckPermissions.checkInsertRights('Bus__c')){
            BusDataBase.queryUpsertBus(bus);
        }        
        else{
            throw new CustomException('InvalidUpsert','Sorry but You do not have permission to change the list of buses',1);
        }  
    }
    
    public static void deleteBus(ModelBox.Bus targetBus){
      
        if(CheckPermissions.checkDeleteRights('Bus__c')){
            BusDataBase.queryToDelete(targetBus);
        }        
        else{
            throw new CustomException('InvalidDelete','Sorry but You do not have permission to delete buses',1);
        }
    }    
}