src/objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bus_Line__c.object
<CustomObject>
    <fields>
        <fullName>Bus__c</fullName>
        <label>Bus</label>
        <referenceTo>Bus__c</referenceTo>
        <relationshipLabel>Bus_Line_relations</relationshipLabel>
        <relationshipName>Bus_Line_relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <referenceTo>Line__c</referenceTo>
        <relationshipLabel>Bus_Line_relations</relationshipLabel>
        <relationshipName>Bus_Line_relations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus_Line</label>
    <nameField>
        <displayFormat>BL-{0000000}</displayFormat>
        <label>Bus_Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus_Line_relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Line__c.object
<CustomObject>
    <label>Line</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ModelBox.cls
public class ModelBox {
    
    public class Bus{
        
        @AuraEnabled public String name            {get; set;}
        @AuraEnabled private Boolean available     {get; set;}
        @AuraEnabled private Id accountOwner       {get; set;}
        @AuraEnabled private Id busId              {get; set;}
        @AuraEnabled private Boolean isEditing     {get; set;}
        @AuraEnabled private List <Line> workLines {get; set;}
        
        
        public Bus(Bus__c bus){ // show bus to "Bus Depot" tab
            this.name         = bus.Name;
            this.available    = bus.Available__c;
            this.accountOwner = bus.Account__c;
            this.busId        = bus.Id;
            this.isEditing    = false;
        }
        public Bus (String accOwner, String name){ // Adding new bus
            this.name         = name;
            this.available    = true;
            this.accountOwner = accOwner;
            this.isEditing    = false;
        }
        
        public Bus(Bus__c bus, List<ModelBox.Line> lines){ // show bus to "Bus Managment" tab
            this.name         = bus.Name;
            this.available    = bus.Available__c;
            this.accountOwner = bus.Account__c;
            this.busId        = bus.Id;
            this.isEditing    = false;
            this.workLines    = lines;
        }
        
        public Bus__c unMap(){
            Bus__c forReturn       = new Bus__c();
            forReturn.Name         = this.name;
            forReturn.Available__c = this.available;
            forReturn.Account__c   = this.accountOwner;
            forReturn.Id           = this.busId;
            return forReturn;
        }
    }    
    public class Line{   
        
        @AuraEnabled  private Id lineId {get; set;}        ///////// LineId.LineName
        @AuraEnabled  private String lineName {get; set;}
        
        
        public Line(Id busOnLineId, String busOnLineName){ 
            this.lineId   =  busOnLineId;
            this.lineName = busOnLineName;
        }        
        
        public Line(Line__c custLine){ 
            this.LineId   =  custLine.Id;
            this.LineName = custLine.Name;
        }        
    }

        public class Bus_Line{   
        
        @AuraEnabled  private Id lineId {get; set;}
        @AuraEnabled  private Id busId  {get; set;}
        
        
        public Bus_Line(Id busId_inp, Id lineId_inp){ 
            this.busId  =  busId_inp;
            this.lineId = lineId_inp;
        }


        public Bus_Line__c convertToCustObj (){

            Bus_Line__c convertedObj = new Bus_Line__c();
            convertedObj.Bus__c  = this.busId;
            convertedObj.Line__c = this.lineId;
            return convertedObj;

        }
    }
    
}